export const GET_VACCINATION_CENTERS_BY_PINCODE =
  'GET_VACCINATION_CENTERS_BY_PINCODE';
export const GET_VACCINATION_CENTERS_BY_DISTRICT =
  'GET_VACCINATION_CENTERS_BY_DISTRICT';
export const GET_VACCINATION_CENTERS_SUCCESS =
  'GET_VACCINATION_CENTERS_SUCCESS';
export const GET_VACCINATION_CENTERS_ERROR = 'GET_VACCINATION_CENTERS_ERROR';
export const GET_VACCINATION_STATES = 'GET_VACCINATION_STATES';
export const GET_VACCINATION_STATES_SUCCESS = 'GET_VACCINATION_STATES_SUCCESS';
export const GET_VACCINATION_STATES_ERROR = 'GET_VACCINATION_STATES_ERROR';
export const GET_VACCINATION_DISTRICTS = 'GET_VACCINATION_DISTRICTS';
export const GET_VACCINATION_DISTRICTS_SUCCESS =
  'GET_VACCINATION_DISTRICTS_SUCCESS';
export const GET_VACCINATION_DISTRICTS_ERROR =
  'GET_VACCINATION_DISTRICTS_ERROR';
export const NOTIFY_ME = 'NOTIFY_ME';
export const NOTIFY_ME_SUCCESS = 'NOTIFY_ME_SUCCESS';
export const NOTIFY_ME_ERROR = 'NOTIFY_ME_ERROR';
export const CLEAR_RESPONSE_MESSAGE = 'CLEAR_RESPONSE_MESSAGE';
