export const GET_VACCINATION_CENTERS_BY_PINCODE =
  'GET_VACCINATION_CENTERS_BY_PINCODE';
export const GET_VACCINATION_CENTERS_BY_DISTRICT =
  'GET_VACCINATION_CENTERS_BY_DISTRICT';
export const GET_VACCINATION_CENTERS_SUCCESS =
  'GET_VACCINATION_CENTERS_SUCCESS';

export const GET_VACCINATION_CENTERS_ERROR = 'GET_VACCINATION_CENTERS_ERROR';
export const SET_SEARCH_BY = 'SET_SEARCH_BY';
