export const GET_COWIN_PUBLIC_REPORT = 'GET_COWIN_PUBLIC_REPORT';
export const GET_COWIN_PUBLIC_REPORT_SUCCESS =
  'GET_COWIN_PUBLIC_REPORT_SUCCESS';
export const GET_COWIN_PUBLIC_REPORT_ERROR = 'GET_COWIN_PUBLIC_REPORT_ERROR';

export const GET_COVID19INDIA_REPORT = 'GET_COVID19INDIA_REPORT';
export const GET_COVID19INDIA_REPORT_SUCCESS =
  'GET_COVID19INDIA_REPORT_SUCCESS';
export const GET_COVID19INDIA_REPORT_ERROR = 'GET_COVID19INDIA_REPORT_ERROR';

export const SET_SELECTED_STATE = 'SET_SELECTED_STATE';
