export const GET_COWIN_PUBLIC_REPORT = 'GET_COWIN_PUBLIC_REPORT';
export const GET_COWIN_PUBLIC_REPORT_SUCCESS =
  'GET_COWIN_PUBLIC_REPORT_SUCCESS';
export const GET_COWIN_PUBLIC_REPORT_ERROR = 'GET_COWIN_PUBLIC_REPORT_ERROR';
